before_all do
  sh 'yarn'
end

desc 'Build android release app'
lane :release_android do
  gradle(task: 'clean', project_dir: 'android/')

  gradle(
    task: 'assemble',
    build_type: 'release',
    project_dir: 'android/'
  )

  firebase_app_distribution(
    app: "1:393145394907:android:ee4e7a1bd63efc360fcefe",
    groups: "testadoresinterno",
    release_notes: "Teste firebase distribution"
  )
end

desc 'Build android debug app'
lane :debug_android do
  gradle(task: 'clean', project_dir: 'android/')

  gradle(
    task: 'assemble',
    build_type: 'debug',
    project_dir: 'android/'
  )
end